// file: src/commands/employees.ts

import { Command } from 'commander';
import chalk from 'chalk';
import apiClient from '../lib/api.ts';

function createWebhooksCommand() {
  const webhooks = new Command('webhooks')
    .description('Manage webhooks in the Greenshades API (list, details, create)');

  webhooks  
    .command('list')  
    .description('Get all webhooks for the workspace')  
    .action(async () => {
      try {        
        console.log(chalk.blue('--- Fetching all webhooks...'));

        const response = await apiClient.get('/webhooks/subscriptions');
        
        console.log(JSON.stringify(response.data, null, 2));
        console.log(chalk.green('✅ Successfully retrieved webhooks.'));

      } catch (error: any) {
        console.error(chalk.red('Error fetching webhooks:', error.message));
        
        process.exit(1);
      }
    });

  webhooks.command('details <webhook-id>')
    .description('Get a single webhook subscription by their Greenshades webhookId')
    .action(async (webhookId) => {
      try {
        console.log(chalk.blue(`Fetching webhook subscription details with subscription Id: ${webhookId}...`));

        const response = await apiClient.get(`/webhooks/subscriptions/${webhookId}`);

        console.log(JSON.stringify(response.data, null, 2));

        console.log(chalk.green(`✅ Successfully retrieved webhook subscription ${webhookId}.`));
      } catch (error: any) {
        console.error(chalk.red(`Error fetching webhook subscription ${webhookId}:`, error.message));

        process.exit(1);
      }
    });

    webhooks.command('create <event-name> <callback-url> [hmac-key]')
    .description('Create a new webhook subscription for a given event name, callback URL, and HMAC key')
    .action(async (eventName, callbackUrl, hmacKey = null) => {
      try {
        const hmacKeyToUse = hmacKey || process.env.GREENSHADES_WEBHOOK_HMAC_KEY;

        console.log(chalk.blue(`--- Creating new webhook subscription for event: ${eventName} with callback URL: ${callbackUrl}...`));
        console.log(chalk.blue(`--- Using HMAC key: ${hmacKeyToUse || 'No HMAC key provided'} (if not provided as argument, will use GREENSHADES_WEBHOOK_HMAC_KEY env variable)`));  
        console.log(eventName, callbackUrl, hmacKeyToUse);
        const response = await apiClient.post(`/webhooks/subscriptions?eventName=${eventName}`, {                                     
            id: 1, // Id will be generated by Greenshades, so we can send an empty string or omit it entirely
            url: callbackUrl,
            hmacKey: hmacKeyToUse,
            subscribedEvents: [ 'payRun.completed' ], // Example events - replace with actual events you want to subscribe to
          });

        console.log(JSON.stringify(response.data, null, 2));

        console.log(chalk.green(`✅ Successfully created webhook subscription for event ${eventName}.`));
      } catch (error: any) {              
        console.error(chalk.red(`Error creating webhook subscription for event ${eventName}:`, error.message));

        process.exit(1);
      }
    });

    webhooks.command('delete <id>')
    .description('Delete a webhook subscription by their Greenshades webhookId')
    .action(async (id) => {
      try {
        console.log(chalk.blue(`--- Deleting webhook subscription with subscription Id: ${id}...`));

        const response = await apiClient.delete(`/webhooks/subscriptions/${id}`);

        console.log(JSON.stringify(response.data, null, 2));

        console.log(chalk.green(`✅ Successfully deleted webhook subscription with Id ${id}.`));
      } catch (error: any) {
        console.error(chalk.red(`Error deleting webhook subscription with Id ${id}:`, error.message));

        process.exit(1);
      }
    });

          
     
    return webhooks;
}

export default createWebhooksCommand;

/***
 * 
 * 
 * 
 
const crypto = require('crypto');

const timestamp = "{{timestamp from RequestHeaders 'X-GS-TIMESTAMP'}}";
const jsonBody = "{{json from RequestBody}}";
const content = timestamp + "\n" + jsonBody;
const key = asciiToHex("my secret key");

const signature = signKey(key, content);

console.log(signature);

function asciiToHex(str) {
	const arr1 = [];
	for (let n = 0, l = str.length; n < l; n++) 
  {
  	const hex = Number(str.charCodeAt(n)).toString(16);
		arr1.push(hex);
	 }
	return arr1.join('');
}

function signKey (clientKey, msg) {
    const key = new Buffer.from(clientKey, 'hex');
    return crypto.createHmac('sha256', key).update(msg).digest('hex');
}

 */